# 生产环境配置
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
# 数据源配置 DES@s67hXzwVvffm04HtYeT7Paq4dStI3tHtT1cSJ_get4-MApbpSr8eBv78ZbvCVyk5paBMJxL_3thM
spring:
  datasource:
    drivername: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.220.88.72:3306/gallery?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: gallery
    password: DES@cUwRBuLxs3ffp3DGsFaw4A
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 600
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
      database: 2
      host: DES@CLi2u7e-YAUO9tVs0YSliBioUhsgdmMLR6LGQ9cD7nh6K2qM4io61hyYeFrl_1I5
      port: 6379
      pass: DES@k-DfKZ166dqpO0DD7wsbMw
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0


aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: DES@32NWPMTGH-ApvXlbRLNuQlJxBuHQqWzg
    accessKeySecret: ydBCcgGiwqNZDrN2d4d1XbL954eYuZ
    bucket: image-gallery
    cdnurl: https://g.yile.vip


wechat:
  miniapp:
    appid: wxe872cecbe6201aca
    secret: DES@Bn_ar_N4296pY9B2Pkqr76I4_dIn1ACNX0x8TZLn57FScQbh0Kls4A
    mchId: 1517295821
    mchKey: DES@G7S_VlwL9qVfseAZfNSAyxvLh8PV4bJGawzTXB_FHzVScQbh0Kls4A
    token: gOcTDdBFEI
    aesKey: L2SgaQOmH2cE4Qw3SLkjw4HefXBoZcbs87poHumzS2X
    msgDataFormat: JSON
  pay:
      appId: wx45d98d2c8e80956f
      mchId: 1517295821
      mchKey: DES@G7S_VlwL9qVfseAZfNSAyxvLh8PV4bJGawzTXB_FHzVScQbh0Kls4A
      subAppId:
      subMchId:
      keyPath:
  mp:
      appId: wx3d912b758d72faa1
      secret: DES@nIJYOt47oS1npE1pxq_vxED5ugS32naiCntbY2f-wfJScQbh0Kls4A
      token: gOcTDdBFEI
      aesKey: L2SgaQOmH2cE4Qw3SLkjw4HefXBoZcbs87poHumzS2X

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      xs:
        daos: debug

gallery:
  domain:
    url: https://gallery.yile.vip
    personUrl: https://gallery.yile.vip/wechat/index.html
    rechargeUrl: https://gallery.yile.vip/wechat/recharge.html
